<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use App\Models\Project;
use App\Models\Skill;
use App\Models\Experience;

class PortfolioRedesignSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        // Projects
        $projects = [
            [
                'title' => 'BTECH Admission System',
                'slug' => 'btech-admissions',
                'description' => 'An automated system for handling student applications, entrance exams, and enrollment workflows for a technical college.',
                'image_path' => '/images/btech-admissions.webp',
                'url' => 'https://btech-admissions.example.com',
                'github_url' => 'https://github.com/kristian03-design/btech-admission',
                'tech_stack' => ['Laravel', 'PHP', 'Tailwind CSS', 'MySQL', 'Vite', 'REST API', 'Git'],
                'category' => 'Web Application',
                'status' => 'Completed',
                'duration' => '6 Months',
                'role' => 'Solo Full-Stack Developer',
                'documentation_url' => 'https://docs.example.com/btech-admissions',
                'video_demo_url' => 'https://youtube.com/embed/dQw4w9WgXcQ',
                'order' => 1,
                'overview' => [
                    'what' => 'An automated admission system for a technical college to manage applicant registrations, entrance examination results, and registration processing.',
                    'why' => 'Built to replace the manual paper-based registration and excel-based sorting, reducing administrative processing time from weeks to hours.',
                    'target_users' => 'College admissions staff, student applicants, and system administrators.',
                    'business_purpose' => 'Streamline student intake, eliminate human errors in grading/sorting, and provide applicants with instant status tracking.',
                    'expected_outcome' => '100% digital admission process with zero lost documents and 80% faster processing.',
                ],
                'gallery' => [
                    'desktop' => '/images/projects/btech-admissions-desktop.webp',
                    'tablet' => '/images/projects/btech-admissions-tablet.webp',
                    'mobile' => '/images/projects/btech-admissions-mobile.webp',
                ],
                'features' => [
                    ['title' => 'Authentication', 'description' => 'Secure role-based login (Applicants, Admin) using Laravel session guards.', 'icon' => 'lock'],
                    ['title' => 'Dashboard', 'description' => 'Real-time statistics on applicants, slots available, and application stages.', 'icon' => 'layout'],
                    ['title' => 'Admin Panel', 'description' => 'Detailed controls for reviewing documents, scheduling exams, and grading.', 'icon' => 'settings'],
                    ['title' => 'Reports Engine', 'description' => 'Export list of qualified students to PDF and Excel dynamically.', 'icon' => 'file-text'],
                    ['title' => 'Notifications', 'description' => 'Automated emails informing applicants about exam schedules and acceptance.', 'icon' => 'bell'],
                ],
                'architecture' => [
                    'system_architecture' => 'Laravel MVC architecture with frontend components rendered via Blade templates. PostgreSQL handles relation persistence while Laravel Cache stores static catalog lists.',
                    'database_erd' => 'users (id, name, email, role) ──< applications (id, user_id, status, batch_id) ──< exam_scores (id, application_id, score, schedule_date)',
                    'folder_structure' => "app/Http/Controllers/AdmissionController.php\napp/Models/Application.php\nresources/views/admission/\nroutes/web.php",
                    'auth_flow' => '1. User enters credentials -> 2. Controller validates via FormRequest -> 3. Auth::attempt() checks bcrypt hash -> 4. Redirects based on user role middleware.',
                    'api_flow' => '1. Axios requests status check -> 2. Middleware verifies token -> 3. Controller returns JSON response -> 4. Frontend updates UI state.',
                ],
                'challenges' => [
                    'problem' => 'Handling over 3,000 concurrent student applications during the final registration day led to query bottlenecks and slow file uploads.',
                    'solution' => 'Optimized queries using Eloquent eager loading (preventing N+1), added database indexes on email and status columns, and integrated chunked uploads.',
                    'result' => 'Reduced server response times from 3.2s to 450ms, maintaining 100% system availability throughout the admission period.',
                ],
                'timeline' => [
                    'planning' => '2 Weeks: Requirement gathering, wireframing, and database design schema verification.',
                    'design' => '2 Weeks: Creating UI/UX components in Figma and establishing the CSS system.',
                    'development' => '12 Weeks: Implementing core modules, controllers, models, and migrations.',
                    'testing' => '4 Weeks: Unit testing controllers, integration testing document upload flows.',
                    'deployment' => '2 Weeks: Hosting on VPS, configuring SSL certificates, and database setups.',
                    'maintenance' => 'Ongoing: Monitoring error logs and applying security patches.',
                ],
                'performance' => [
                    'lazy_loading' => 'Used on images and paginated student lists.',
                    'caching' => 'Configured Laravel database cache for static courses.',
                    'image_optimization' => 'Compressed all applicant uploaded profile photos to WebP.',
                    'seo' => 'Fully optimized meta tags, JSON-LD schema, and clean SEO URLs.',
                    'performance_score' => 96,
                    'accessibility' => 92,
                ],
                'security_details' => [
                    'csrf' => 'CSRF tokens generated and verified on all POST/PUT/DELETE forms.',
                    'xss' => 'Double curly braces in Blade escape HTML tags.',
                    'sql_injection' => 'PDO parameter bindings protect all database operations.',
                    'authentication' => 'Secure session authentication built on Laravel middleware.',
                    'authorization' => 'Policy gates restrict user actions on applicant records.',
                    'validation' => 'Strict server-side validation using FormRequest.',
                    'file_upload' => 'Mime-type verification and file renaming for uploaded PDFs.',
                    'rate_limiting' => 'Throttle middleware on logins (max 5 requests per minute).',
                    'secure_sessions' => 'Encrypted HTTP-only cookies and database session storage.',
                    'env_variables' => 'All database and SMTP credentials isolated in .env.',
                ],
                'metrics' => [
                    'loc' => '12,500',
                    'db_tables' => '14',
                    'api_endpoints' => '24',
                    'modules' => '6',
                    'completion_date' => '2023-12-31',
                    'development_time' => '6 Months',
                ],
            ],
            [
                'title' => 'CourtConnect',
                'slug' => 'courtconnect',
                'description' => 'A sports court reservation and schedule management system for municipal and private sports facilities.',
                'image_path' => '/images/projects/courtconnect-desktop.webp',
                'url' => 'https://courtconnect.example.com',
                'github_url' => 'https://github.com/kristian03-design/courtconnect',
                'tech_stack' => ['Laravel', 'PHP', 'Tailwind CSS', 'PostgreSQL', 'Vite', 'REST API', 'Git', 'Docker'],
                'category' => 'Web Application',
                'status' => 'Completed',
                'duration' => '3 Months',
                'role' => 'Solo Developer',
                'documentation_url' => 'https://docs.example.com/courtconnect',
                'video_demo_url' => 'https://youtube.com/embed/dQw4w9WgXcQ',
                'order' => 2,
                'overview' => [
                    'what' => 'An online court reservation and scheduling system that allows users to book basketball, tennis, and badminton courts, while giving owners management tools.',
                    'why' => 'Developed to prevent double-booking issues and provide convenient booking options outside regular business hours.',
                    'target_users' => 'Local athletes, court managers, and community center coordinators.',
                    'business_purpose' => 'Optimize court usage rates, automate booking workflows, and secure payments.',
                    'expected_outcome' => 'Zero schedule overlaps, decreased booking administrative tasks by 90%, and secure online checkout.',
                ],
                'gallery' => [
                    'desktop' => '/images/projects/courtconnect-desktop.webp',
                    'tablet' => '/images/projects/courtconnect-tablet.webp',
                    'mobile' => '/images/projects/courtconnect-mobile.webp',
                ],
                'features' => [
                    ['title' => 'Interactive Calendar', 'description' => 'View hourly court availability and book slots via calendar drag-select.', 'icon' => 'calendar'],
                    ['title' => 'Booking System', 'description' => 'Automated reservation locks to prevent race conditions during booking.', 'icon' => 'clock'],
                    ['title' => 'Payment Portal', 'description' => 'Integrated payment flow for booking reservation fees.', 'icon' => 'credit-card'],
                    ['title' => 'Admin Dashboard', 'description' => 'Manage court inventory, rates, peak hours, and check revenue reports.', 'icon' => 'bar-chart'],
                ],
                'architecture' => [
                    'system_architecture' => 'Laravel backend exposing JSON endpoints for a dynamic calendar fronted by Tailwind CSS.',
                    'database_erd' => 'courts (id, name, hourly_rate) ──< bookings (id, court_id, user_id, start_time, end_time, status)',
                    'folder_structure' => "app/Http/Controllers/BookingController.php\napp/Models/Court.php\nresources/views/bookings/",
                    'auth_flow' => 'Standard session auth with registration validation email verification.',
                    'api_flow' => 'Fetch calendar events -> controller computes slot availability -> returns availability ranges as JSON.',
                ],
                'challenges' => [
                    'problem' => 'Two users booking the same court at the exact same millisecond caused double-booking errors.',
                    'solution' => 'Implemented database transaction isolation levels and unique index constraints combining court_id, start_time, and end_time.',
                    'result' => '100% booking accuracy with zero double bookings recorded in production testing.',
                ],
                'timeline' => [
                    'planning' => '1 Week: Database locking design and calendar component evaluation.',
                    'design' => '2 Weeks: Creating clean dark-themed booking templates.',
                    'development' => '6 Weeks: Implementation of booking logics, calendar updates, and stripe webhook triggers.',
                    'testing' => '2 Weeks: Concurrency tests and payment flow mock runs.',
                    'deployment' => '1 Week: Deployment via Docker containers on AWS EC2.',
                    'maintenance' => 'Ongoing.',
                ],
                'performance' => [
                    'lazy_loading' => 'Lazy-loaded full calendar scripts until reservation view is activated.',
                    'caching' => 'Cached court metadata for fast loads.',
                    'image_optimization' => 'WebP compression.',
                    'seo' => 'Optimized keywords, local SEO schema.',
                    'performance_score' => 98,
                    'accessibility' => 94,
                ],
                'security_details' => [
                    'csrf' => 'CSRF verification enabled.',
                    'xss' => 'Blade secure outputs.',
                    'sql_injection' => 'Eloquent ORM parameterized queries.',
                    'authentication' => 'Role-based authorization middleware.',
                    'authorization' => 'Users can only edit or cancel their own bookings.',
                    'validation' => 'No overlapping slots validation rules in form requests.',
                    'file_upload' => 'No public file uploads required.',
                    'rate_limiting' => 'Rate-limiting booking attempts to 5 per minute per user.',
                    'secure_sessions' => 'Database session driver.',
                    'env_variables' => 'Secure Stripe API keys in .env.',
                ],
                'metrics' => [
                    'loc' => '8,400',
                    'db_tables' => '9',
                    'api_endpoints' => '16',
                    'modules' => '4',
                    'completion_date' => '2024-03-15',
                    'development_time' => '3 Months',
                ],
            ],
            [
                'title' => 'Williams Record Store',
                'slug' => 'williams-record-store',
                'description' => 'A dynamic online shop for music records, vinyl collectors, and boutique audio gear.',
                'image_path' => '/images/projects/williams-record-store-desktop.webp',
                'url' => 'https://williams-records.example.com',
                'github_url' => 'https://github.com/kristian03-design/williams-record-store',
                'tech_stack' => ['Laravel', 'PHP', 'Tailwind CSS', 'MySQL', 'JavaScript', 'Git', 'Vite'],
                'category' => 'Web Application (E-Commerce)',
                'status' => 'Completed',
                'duration' => '2 Months',
                'role' => 'Solo Full-Stack Developer',
                'documentation_url' => 'https://docs.example.com/williams-records',
                'video_demo_url' => null,
                'order' => 3,
                'overview' => [
                    'what' => 'An e-commerce platform specifically styled for music record stores, featuring vinyl preview players, advanced music filtering, and a shopping checkout workflow.',
                    'why' => 'Built to provide record collectors with a digital store that replicates the sensory experience of browsing a physical shop.',
                    'target_users' => 'Vinyl collectors, audio enthusiasts, and independent music shop owners.',
                    'business_purpose' => 'Establish a premium online brand store to sell records and merchandise directly to consumers.',
                    'expected_outcome' => 'A visually rich e-commerce system that loads pages instantly and offers seamless checkout.',
                ],
                'gallery' => [
                    'desktop' => '/images/projects/williams-record-store-desktop.webp',
                    'tablet' => '/images/projects/williams-record-store-tablet.webp',
                    'mobile' => '/images/projects/williams-record-store-mobile.webp',
                ],
                'features' => [
                    ['title' => 'Digital Player Preview', 'description' => 'Listen to audio preview snippets from albums using a stylized spinning record player.', 'icon' => 'music'],
                    ['title' => 'Shopping Cart', 'description' => 'Fully local-storage backed shopping cart with session sync.', 'icon' => 'shopping-bag'],
                    ['title' => 'Advanced Filtering', 'description' => 'Filter catalog by Genre, Release Year, Condition, and Artist.', 'icon' => 'sliders'],
                    ['title' => 'Checkout API', 'description' => 'Integrated payment flow with instant receipt emails.', 'icon' => 'check-circle'],
                ],
                'architecture' => [
                    'system_architecture' => 'Laravel Web App using Blade and Tailwind CSS. The shopping cart resides on the client side with secure server-side verification before payment processing.',
                    'database_erd' => 'products (id, title, artist, price) ──< order_items (id, order_id, product_id, quantity) ──< orders (id, total, status)',
                    'folder_structure' => "app/Http/Controllers/ProductController.php\nresources/views/shop/",
                    'auth_flow' => 'Guest checkout supported, optional user account signup.',
                    'api_flow' => 'Verification endpoint check stock -> processes charge via payment gateway -> callback records order.',
                ],
                'challenges' => [
                    'problem' => 'Record collections contain extensive metadata, which made keyword searches sluggish and inefficient when database tables grew.',
                    'solution' => 'Implemented MySQL full-text indices and optimized database queries using indexes on genre and release columns.',
                    'result' => 'Catalog search queries returned results in less than 30ms.',
                ],
                'timeline' => [
                    'planning' => '1 Week: Product schema design and payment integrations planning.',
                    'design' => '1 Week: High-fidelity styling incorporating custom spinning records animations.',
                    'development' => '4 Weeks: Shopping cart logic, filter endpoints, admin product management.',
                    'testing' => '1 Week: Testing webhook flows and cross-browser layouts.',
                    'deployment' => '1 Week: Production launch.',
                ],
                'performance' => [
                    'lazy_loading' => 'Lazy-loaded record cover images and audio files.',
                    'caching' => 'Cached homepage best sellers lists.',
                    'image_optimization' => 'Converted heavy JPG covers into compressed WebPs.',
                    'seo' => 'Individual product pages optimized for search engines.',
                    'performance_score' => 95,
                    'accessibility' => 91,
                ],
                'security_details' => [
                    'csrf' => 'CSRF tokens enforced.',
                    'xss' => 'Strict HTML escaping.',
                    'sql_injection' => 'Eloquent parameter binding.',
                    'authentication' => 'Optional login via Laravel fortify schema.',
                    'authorization' => 'Admin role required to access stock editing.',
                    'validation' => 'Strict form requests validation for reviews.',
                    'file_upload' => 'Product images upload restricted to admin auth, mime verified.',
                    'rate_limiting' => 'Rate limiter on API routes.',
                    'secure_sessions' => 'Encrypted sessions.',
                    'env_variables' => 'API secret keys isolated in .env.',
                ],
                'metrics' => [
                    'loc' => '6,800',
                    'db_tables' => '7',
                    'api_endpoints' => '12',
                    'modules' => '3',
                    'completion_date' => '2024-05-10',
                    'development_time' => '2 Months',
                ],
            ],
            [
                'title' => 'Job Tracker',
                'slug' => 'job-tracker',
                'description' => 'A productivity Kanban dashboard helping job seekers organize and track applications, interviews, and offers.',
                'image_path' => '/images/projects/job-tracker-desktop.webp',
                'url' => 'https://jobtracker.example.com',
                'github_url' => 'https://github.com/kristian03-design/job-tracker',
                'tech_stack' => ['Laravel', 'PHP', 'JavaScript', 'Tailwind CSS', 'MySQL', 'Git', 'Vite'],
                'category' => 'Web Application',
                'status' => 'Completed',
                'duration' => '4 Months',
                'role' => 'Lead Developer',
                'documentation_url' => null,
                'video_demo_url' => null,
                'order' => 4,
                'overview' => [
                    'what' => 'A personal Kanban board layout application where users drag-and-drop job application cards across Wishlist, Applied, Interviewing, Offer, and Rejected stages.',
                    'why' => 'Designed to help job hunters keep track of multiple job openings, files (resumes, cover letters), and interview calendar dates in one place.',
                    'target_users' => 'Job seekers, graduates, and professionals in career transition.',
                    'business_purpose' => 'Provide a focused productivity tool to organize candidate workflows and increase follow-up efficiency.',
                    'expected_outcome' => 'Organized job application records, automated calendar reminders, and analytics on application-to-interview ratios.',
                ],
                'gallery' => [
                    'desktop' => '/images/projects/job-tracker-desktop.webp',
                    'tablet' => '/images/projects/job-tracker-tablet.webp',
                    'mobile' => '/images/projects/job-tracker-mobile.webp',
                ],
                'features' => [
                    ['title' => 'Kanban Board', 'description' => 'Interactive board interface with smooth drag-and-drop to update stages.', 'icon' => 'columns'],
                    ['title' => 'Document Center', 'description' => 'Upload resumes and cover letters linked specifically to each job application card.', 'icon' => 'folder-open'],
                    ['title' => 'Interview Calendar', 'description' => 'Add interview dates and sync with local timezone reminders.', 'icon' => 'calendar'],
                    ['title' => 'Analytics', 'description' => 'Generate charts displaying success rates, average rejection response times, and application channels.', 'icon' => 'pie-chart'],
                ],
                'architecture' => [
                    'system_architecture' => 'Laravel backend providing REST routes to a drag-and-drop JavaScript board. Files are secured on local storage disk under protected user directories.',
                    'database_erd' => 'users (id) ──< applications (id, company, position, status, order_index) ──< contacts (id, application_id, name, email)',
                    'folder_structure' => "app/Http/Controllers/JobController.php\napp/Models/Application.php\nresources/js/kanban.js",
                    'auth_flow' => 'Standard user registration and login.',
                    'api_flow' => 'Drag card -> AJAX request transmits new status stage and index -> backend shifts card ordering.',
                ],
                'challenges' => [
                    'problem' => 'Managing the dynamic sorting order of multiple cards in different lists led to race condition sorting errors on database updates.',
                    'solution' => 'Implemented an index re-ordering algorithm in the controller that updates positions in a single transaction database sequence.',
                    'result' => 'Smooth, bug-free drag interactions with instantaneous database syncing.',
                ],
                'timeline' => [
                    'planning' => '2 Weeks: Wireframing the board layout and deciding sorting algorithms.',
                    'design' => '2 Weeks: Designing minimal templates focusing on visual data clarity.',
                    'development' => '8 Weeks: Implementation of kanban logics, file uploads, and reminder systems.',
                    'testing' => '3 Weeks: Testing card drag edge cases and upload mime validation.',
                    'deployment' => '1 Week: Hosted on cloud infrastructure.',
                ],
                'performance' => [
                    'lazy_loading' => 'Lazy-loaded dashboard graphs and analytics scripts.',
                    'caching' => 'Cached dashboard summary numbers.',
                    'image_optimization' => 'Minimal image reliance; optimized vector icons.',
                    'seo' => 'Optimized landing page SEO.',
                    'performance_score' => 97,
                    'accessibility' => 95,
                ],
                'security_details' => [
                    'csrf' => 'CSRF tokens verified on all AJAX requests.',
                    'xss' => 'Strict data sanitization before rendering JSON data.',
                    'sql_injection' => 'Prepared queries strictly.',
                    'authentication' => 'Middleware guard on all dashboard routes.',
                    'authorization' => 'Strict policy authorization ensuring users can only read/edit their own cards.',
                    'validation' => 'Validate file uploads strictly (limit to PDF, DOCX up to 2MB).',
                    'file_upload' => 'Files stored in non-public folders; served using signed streams.',
                    'rate_limiting' => 'Rate limiter on API routes.',
                    'secure_sessions' => 'Database session driver.',
                    'env_variables' => 'Isolated configs.',
                ],
                'metrics' => [
                    'loc' => '9,500',
                    'db_tables' => '8',
                    'api_endpoints' => '18',
                    'modules' => '5',
                    'completion_date' => '2024-09-20',
                    'development_time' => '4 Months',
                ],
            ],
            [
                'title' => 'GBLDC Mobile Loan Application',
                'slug' => 'gbldc-loan-app',
                'description' => 'A comprehensive mobile solution for managing loan applications, featuring real-time status tracking and secure document uploads.',
                'image_path' => '/images/projects/gbldc-loan-app-desktop.webp',
                'url' => '#',
                'github_url' => 'https://github.com/kristian03-design/gbldc-mobile',
                'tech_stack' => ['Flutter', 'Dart', 'Firebase', 'REST API', 'Git'],
                'category' => 'Mobile Application',
                'status' => 'Completed',
                'duration' => '5 Months',
                'role' => 'Lead Mobile Developer',
                'documentation_url' => 'https://docs.example.com/gbldc',
                'video_demo_url' => 'https://youtube.com/embed/dQw4w9WgXcQ',
                'order' => 5,
                'overview' => [
                    'what' => 'A mobile application built with Flutter that enables applicants to apply for loans, submit documentation, track application statuses, and chat with loan officers.',
                    'why' => 'Designed to streamline the microfinance loan processing workflow, eliminating physical queues and reducing processing turnaround from 14 days to 48 hours.',
                    'target_users' => 'Borrowers, microfinance agents, and credit underwriters.',
                    'business_purpose' => 'Digitize credit scoring collection, secure client records, and speed up loan approvals.',
                    'expected_outcome' => 'High application intake rates, automated document extraction, and seamless real-time notifications.',
                ],
                'gallery' => [
                    'desktop' => '/images/projects/gbldc-loan-app-desktop.webp',
                    'tablet' => '/images/projects/gbldc-loan-app-tablet.webp',
                    'mobile' => '/images/projects/gbldc-loan-app-mobile.webp',
                ],
                'features' => [
                    ['title' => 'Biometric Auth', 'description' => 'Fingerprint and FaceID login integration for fast, secure access.', 'icon' => 'shield'],
                    ['title' => 'Camera Scanner', 'description' => 'Capture, crop, and compress documents (IDs, payslips) to PDF dynamically on device.', 'icon' => 'camera'],
                    ['title' => 'Real-Time Tracker', 'description' => 'Live step progress indicators displaying application statuses.', 'icon' => 'trending-up'],
                    ['title' => 'Push Notifications', 'description' => 'Receive instant alerts regarding underwriting requests and loan payouts.', 'icon' => 'smartphone'],
                ],
                'architecture' => [
                    'system_architecture' => 'Flutter Client structured with Clean Architecture using BLoC state management. Integrates with Firebase Auth, Firestore Database, and Supabase Storage via REST APIs.',
                    'database_erd' => 'NoSQL Collections: users (uid, name), loans (loan_id, user_uid, amount, status), chat_rooms (room_id, participants)',
                    'folder_structure' => "lib/features/loan/presentation/bloc/\nlib/features/loan/domain/usecases/\nlib/features/loan/data/repositories/",
                    'auth_flow' => 'Firebase Authentication with JSON Web Tokens (JWT) validating request security headers.',
                    'api_flow' => 'Client submits loan data -> payload processed via server API -> results saved to Firestore -> triggers agent approval dashboard.',
                ],
                'challenges' => [
                    'problem' => 'Uploading high-resolution scans of applicant documents caused mobile network timeouts in rural areas with poor connectivity.',
                    'solution' => 'Implemented client-side image compression (downscaling and conversion to WebP) and background upload retries using SQLite queue syncing.',
                    'result' => 'Successful upload rates increased to 99.4%, even under weak 3G signals.',
                ],
                'timeline' => [
                    'planning' => '2 Weeks: Wireframing mobile screens, planning Firebase DB security rules.',
                    'design' => '3 Weeks: High-fidelity screens and custom components in Figma.',
                    'development' => '10 Weeks: Core Flutter BLoC implementation, storage APIs integrations.',
                    'testing' => '3 Weeks: Testing offline states, sync capabilities, and emulator validations.',
                    'deployment' => '2 Weeks: Releasing application packages on Google Play Store and Apple App Store.',
                ],
                'performance' => [
                    'lazy_loading' => 'Lazy-loaded lists using listview builders.',
                    'caching' => 'Cached images and network assets locally using SQLite DB.',
                    'image_optimization' => 'On-device compression prior to upload.',
                    'seo' => 'Store pages optimized with proper keywords.',
                    'performance_score' => 94,
                    'accessibility' => 93,
                ],
                'security_details' => [
                    'csrf' => 'CSRF verification on secure API endpoints.',
                    'xss' => 'Dynamic string content escaped properly in Dart.',
                    'sql_injection' => 'Parameters bound securely in internal SQLite lists.',
                    'authentication' => 'Secure Biometrics + Firebase JWT tokens verification.',
                    'authorization' => 'Firebase Security Rules preventing unauthorized document reads.',
                    'validation' => 'Validation on input fields prior to API submit.',
                    'file_upload' => 'Mime types validation on backend REST handlers.',
                    'rate_limiting' => 'Rate limiter on API routes.',
                    'secure_sessions' => 'Encrypted secure storage used on device for authentication state tokens.',
                    'env_variables' => 'Secrets managed via Dart environment parameters.',
                ],
                'metrics' => [
                    'loc' => '18,200',
                    'db_tables' => '0 (NoSQL)',
                    'api_endpoints' => '14',
                    'modules' => '5',
                    'completion_date' => '2024-11-30',
                    'development_time' => '5 Months',
                ],
            ],
        ];

        foreach ($projects as $project) {
            Project::updateOrCreate(['title' => $project['title']], $project);
        }

        // Skills
        $skills = [
            ['name' => 'HTML', 'category' => 'Frontend', 'proficiency_level' => 95],
            ['name' => 'CSS', 'category' => 'Frontend', 'proficiency_level' => 90],
            ['name' => 'JavaScript', 'category' => 'Frontend', 'proficiency_level' => 85],
            ['name' => 'Tailwind CSS', 'category' => 'Frontend', 'proficiency_level' => 95],
            ['name' => 'Flutter', 'category' => 'Frontend', 'proficiency_level' => 80],
            ['name' => 'PHP', 'category' => 'Backend', 'proficiency_level' => 90],
            ['name' => 'Laravel', 'category' => 'Backend', 'proficiency_level' => 85],
            ['name' => 'MySQL', 'category' => 'Backend', 'proficiency_level' => 85],
            ['name' => 'REST API', 'category' => 'Backend', 'proficiency_level' => 80],
            ['name' => 'GitHub', 'category' => 'Tools', 'proficiency_level' => 90],
            ['name' => 'Vercel', 'category' => 'Tools', 'proficiency_level' => 80],
            ['name' => 'Firebase', 'category' => 'Tools', 'proficiency_level' => 75],
            ['name' => 'Supabase', 'category' => 'Tools', 'proficiency_level' => 70],
            ['name' => 'Figma', 'category' => 'Tools', 'proficiency_level' => 75],
        ];

        foreach ($skills as $skill) {
            Skill::updateOrCreate(['name' => $skill['name']], $skill);
        }

        // Experiences
        $experiences = [
            [
                'role' => 'Entry-Level Developer',
                'company' => 'Freelance & Personal Projects',
                'description' => 'Focusing on Laravel and Flutter development. Building real-world systems like GBLDC and OJT Trackers to solve specific operational challenges.',
                'start_date' => '2023-01-01',
                'is_current' => true,
            ],
            [
                'role' => 'Web Development Intern',
                'company' => 'BTECH Admission Office',
                'description' => 'Developed the Admission Office System using Laravel. Focused on automating student intake and exam scheduling workflows.',
                'start_date' => '2023-06-01',
                'end_date' => '2023-12-31',
                'is_current' => false,
            ],
        ];

        foreach ($experiences as $exp) {
            Experience::updateOrCreate(['role' => $exp['role'], 'company' => $exp['company']], $exp);
        }
    }
}
